-- MySQL Script generated by MySQL Workbench

-- Fri Sep 28 09:19:02 2018
-- Model: New Model    Version: 1.0

-- MySQL Workbench Forward Engineering



SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;

SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Schema mydb

-- -----------------------------------------------------

DROP SCHEMA IF EXISTS `proyectolittle` ;


-- -----------------------------------------------------

-- Schema mydb

-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `proyectolittle` DEFAULT CHARACTER SET utf8 ;

-- -----------------------------------------------------

-- Schema new_schema1

-- -----------------------------------------------------

USE `proyectolittle` ;


-- -----------------------------------------------------

-- Table `proyectolittle`.`clientes`

-- -----------------------------------------------------

DROP TABLE IF EXISTS `proyectolittle`.`clientes` ;


CREATE TABLE IF NOT EXISTS `proyectolittle`.`clientes` (
  
`nif` VARCHAR(9) NOT NULL,
  
`nombre` VARCHAR(30) NULL,
  
`direcc` VARCHAR(70) NULL,
  
PRIMARY KEY (`nif`))
ENGINE = InnoDB;



-- -----------------------------------------------------

-- Table `proyectolittle`.`articulos`

-- -----------------------------------------------------

DROP TABLE IF EXISTS `proyectolittle`.`articulos` ;


CREATE TABLE IF NOT EXISTS `proyectolittle`.`articulos` (
  
`CodArt` INT NOT NULL,
  
`nombreArt` VARCHAR(45) NULL,
  
`precio` INT NULL,
  
PRIMARY KEY (`CodArt`))
ENGINE = InnoDB;



-- -----------------------------------------------------

-- Table `proyectolittle`.`facturas`

-- -----------------------------------------------------

DROP TABLE IF EXISTS `proyectolittle`.`facturas` ;


CREATE TABLE IF NOT EXISTS `proyectolittle`.`facturas` (
  
`codFact` INT NOT NULL AUTO_INCREMENT,
  
`importe` INT NULL,
  
`total` DECIMAL NULL,
  
`nif` VARCHAR(9) NULL,
  
PRIMARY KEY (`codFact`),  
  
CONSTRAINT `nif`
    
FOREIGN KEY (`nif`)
    
REFERENCES `proyectolittle`.`clientes` (`nif`)
    
ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------

-- Table `proyectolittle`.`artFact`

-- -----------------------------------------------------

DROP TABLE IF EXISTS `proyectolittle`.`artFact` ;


CREATE TABLE IF NOT EXISTS `proyectolittle`.`artFact` (
  
`codArt` INT NOT NULL,
  
`codFact` INT NOT NULL,
  
`precio` DECIMAL NULL,
  
`cantidad` INT NULL,
  
`nombreArt` VARCHAR(45) NULL,
  
PRIMARY KEY (`codArt`, `codFact`),
  
CONSTRAINT `codFact`
    
FOREIGN KEY (`codFact`)
    
REFERENCES `proyectolittle`.`facturas` (`codFact`)
    
ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  
CONSTRAINT `codArt`
    FOREIGN KEY (`codArt`)
    
REFERENCES `proyectolittle`.`articulos` (`CodArt`)
    
ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




SET SQL_MODE=@OLD_SQL_MODE;

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;

SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
